version: '3'
services:
  ecommerce-app:
    container_name: ecommerce-app
    image: murugesh1996/ecommercemonolithicbackend
    restart: always
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql

  docker-mysql:
    container_name: docker-mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_ROOT_PASSWORD: ecommerceapp
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./ecommerce.sql:/docker-entrypoint-initdb.d/ecommerce.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""]
      interval: 4s
      timeout: 20s
      retries: 5
      start_period: 30s

  ecommerce-frontend:
    image: murugesh1996/angular-ecommerce-monolithic-local
    ports:
      - "4200:80"
      - "49153:49153"
